{% set version = "2.0.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geiger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geiger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geiger/geiger_{{ version }}.tar.gz
  sha256: c8c8c871b4eb03ba1dc2fd49db304741b16ede99fe49bb5f9b2c220b9e2a8066

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - r-base
    - r-mass
    - r-rcpp >=0.11.0
    - r-coda
    - r-colorspace
    - r-desolve >=1.7
    - r-digest
    - r-mvtnorm
    - r-ncbit
    - r-subplex
    - r-phytools >=0.7.31
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-rcpp >=0.11.0
    - r-coda
    - r-colorspace
    - r-desolve >=1.7
    - r-digest
    - r-mvtnorm
    - r-ncbit
    - r-subplex
    - r-phytools >=0.7.31

test:
  commands:
    - $R -e "library('geiger')"           # [not win]
    - "\"%R%\" -e \"library('geiger')\""  # [win]

about:
  home: http://www.webpages.uidaho.edu/~lukeh/software.html
  license: GPL-2.0-or-later
  summary: Methods for fitting macroevolutionary models to phylogenetic trees.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: geiger
# Type: Package
# Title: Analysis of Evolutionary Diversification
# Version: 2.0.6.2
# Date: 2015-09-07
# Author: Luke Harmon <lukeh@uidaho.edu>, Jason Weir, Chad Brock, Rich Glor, Wendell Challenger, Gene Hunt, Rich FitzJohn, Matt Pennell, Graham Slater, Joseph Brown, Josef Uyeda, and Jon Eastman <jonathan.eastman@gmail.com>
# Maintainer: ORPHANED
# Depends: ape (>= 3.0-6), R (>= 2.15.0)
# Imports: MASS, mvtnorm, subplex, deSolve (>= 1.7), digest, Rcpp (>= 0.11.0), coda, ncbit, colorspace, methods
# LinkingTo: Rcpp
# Description: Methods for fitting macroevolutionary models to phylogenetic trees.
# License: GPL (>= 2)
# URL: http://www.webpages.uidaho.edu/~lukeh/software.html
# ByteCompile: yes
# NeedsCompilation: yes
# Packaged: 2019-06-04 09:54:12 UTC; ripley
# Repository: CRAN
# Date/Publication: 2019-06-04 10:19:01 UTC
# X-CRAN-Original-Maintainer: Matt Pennell <mwpennell@gmail.com>
# X-CRAN-Comment: Orphaned and corrected on 2019-01-16 as no response to request for corrections.
