travis:
  secure:
    BINSTAR_TOKEN: sW5cfJaScJqzqHkCGxPzAQL1l4sRElUSnzJ3xLWWToP721fPh92Zf/qgP5Q5Mmyf53HoJUHE5J2CaDM1AU5/8yIeRxFylOGKJHBUn01yuOeSUrr9Wmn/RSedegaKHUAuVoVrrLnc0m/7V2XbNSpYoES/Vz+x2azjUszgb4qmws1MH8lS4qItH6LDq1xk7ImEW2wSp6mMNz/PTQ3R1hFYHxiB04RBH9Lz3FbGlR0rVXDWw+iJ93MiTLBBKhri5zIo9WtfqtVN1XaOjygGheg+ro+w3qjGU8V9oRdwYYc4MgMsUQpU5kpOVOIFQWyIhRRYFUkFVVjk/47Kiyd356CTrL5sjFhuaDjmfnBKf9Pwwor20+RJLtzDjZ6/1cCjboWQWpt9nf8FJf/nIL3thO6bLsSIZj/80q8vUUvce5UIGOA6dVcPp95vbUs+XzMEWR1AaXFQILeG6/X/xO6996F6AlhJQ44V1w3BBs5meKLW4IXfN4FOBgQUsZMukikwLc+nS8j6hkQiMsTZL/b2MW+J8myVYfsIvZv65VLWfyY0uG/OzDNY5eKrA+yAl0vXnTEkWuWG0/x3kXp0MbAPLFxjXymPzRXnCcshCLxifVcl6E+QYPbZSVSl9R2PmLmzbgMsKKHfen2gSUG+0z5nyxQxBISZzHU7Z3+6Le9Zl+lMwuo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
